### ISSUE TITLE
Sift-O-Tron 250 Nodes Incorrectly Placed

### ISSUE THREAD

**Issue by TylerFBenson** [post-kerbin-mining-corporation/FarFutureTechnologies#106]
Looks like the attach nodes on the Sift-O-Tron Atmosphere Processor are rotated by 90 degrees from where they should be.

![](https://i.imgur.com/KqFLnF4.png)

**Comment by TylerFBenson** [comment]
Need to verify this is present in a clean install, more info to come.

**Comment by ra4nd0m** [comment]
Can confirm that on a clean install
![image](https://user-images.githubusercontent.com/58385866/97777231-d26baa80-1b7f-11eb-971d-e24d21b6d309.png)

**Comment by ChrisAdderley** [comment]
-> SpaceDust, but this is technically the model being rotated incorrectly

**Comment by ChrisAdderley** [comment]
Fixed with latest version of SpaceDust
