### ISSUE TITLE
Gold foil Heinlein NSWR missing interior texture

### ISSUE THREAD

**Issue by TylerFBenson** [post-kerbin-mining-corporation/FarFutureTechnologies#107]
No texturing in the interior of the gold foil variant of the Heinlein NSWR engine.

![](https://i.imgur.com/ZCcuZK4.png)

**Comment by TylerFBenson** [comment]
Need to verify this is present in a clean install, more info to come.

**Comment by ra4nd0m** [comment]
Can confirm that on a clean install. 
![image](https://user-images.githubusercontent.com/58385866/97777191-a0f2df00-1b7f-11eb-981c-85621f2fbe32.png)

**Comment by ChrisAdderley** [comment]
Fixed in 0.9.1
