### ISSUE TITLE
Broken localization strings on few parts

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/FarFutureTechnologies#108]
![image](https://user-images.githubusercontent.com/58385866/97777400-0398aa80-1b81-11eb-9dca-d6c49286c4d5.png)
![image](https://user-images.githubusercontent.com/58385866/97777413-127f5d00-1b81-11eb-802c-13844e171a9d.png)

**Comment by ra4nd0m** [comment]
On Lithium tanks without NF suite manufacturer strings also broken
![image](https://user-images.githubusercontent.com/58385866/97777480-8b7eb480-1b81-11eb-804a-1cfd6cc17ae9.png)

**Comment by ra4nd0m** [comment]
![image](https://user-images.githubusercontent.com/58385866/97803644-cf45ec80-1c5b-11eb-84e4-98ade524d29f.png)
broken localization in deuterium only mode

**Comment by ChrisAdderley** [comment]
Resolved these, but keep this open to add more.

**Comment by ChrisAdderley** [comment]
0.9.1 fixes all noted above.

**Comment by ra4nd0m** [comment]
![image](https://user-images.githubusercontent.com/58385866/97867995-f665f200-1d1f-11eb-94ca-75709513c4e1.png)
It seems that this button should mean "Stop Charging Capacitors"

**Comment by ChrisAdderley** [comment]
That last is fixed in 0.9.4
