### ISSUE TITLE
Engine FX glitching through the model on NSWR

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/FarFutureTechnologies#109]
![image](https://user-images.githubusercontent.com/58385866/97777584-5de63b00-1b82-11eb-9b68-b1d9c6c090bd.png)

**Comment by ChrisAdderley** [comment]
hmm, will have to think about this, it's not really solveable

**Comment by ChrisAdderley** [comment]
Minimized in next version
