### ISSUE TITLE
Typo (maybe) in fusion fuel tank description

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/FarFutureTechnologies#111]
ST-4L3R Fusion Fuel Tank have repeats in its description
![image](https://user-images.githubusercontent.com/58385866/97807450-ef80a600-1c71-11eb-8a5c-becd9ae1a411.png)

**Comment by ra4nd0m** [comment]
#LOC_FFT_fft-fueltank-fusion-375-2_description = Some structural variants are available for more mounting options. Deuterium and He3 are provided in the proper ratios for fusion applications. Some structural variants are available for more mounting options.

line №192

**Comment by ChrisAdderley** [comment]
This is more description exhaustion than a typo.
