### ISSUE TITLE
Compatibility with PersistentThrust

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/FarFutureTechnologies#115]
log + vid:
https://drive.google.com/drive/folders/1JAxpAg2gAC3MFTiGI-1H9zAliNI3sMcR?usp=sharing
Please note: the game was closed with Alt+F4

**Comment by ChrisAdderley** [comment]
Can you explain this? The video being in Russian kinda makes it hard to track what is going on. What I see is the engine stopping working when power runs out which is as expected.

**Comment by ra4nd0m** [comment]
Yes but despite it shows up like it does not produce any thrust (there are zeroes in "thrust" section.
Actually it still produces little to no thrust as can be seen in the video that the ship is not falling but instead hovering on one place while slowly rising

**Comment by ra4nd0m** [comment]
Also please take a note at insanely fast changing numbers in the card. Those numbers should show current electricity consumption.
Instead of showing zero they spontaneously change

**Comment by ChrisAdderley** [comment]
Oh, weird. Will have to look into that further - this engine is very stock in terms of code so maybe it is misconfigured somehow.

**Comment by ra4nd0m** [comment]
I repeatedly hover mouse around those.
3. When electricity runs out the plume animation continues playing on full thrust

**Comment by ChrisAdderley** [comment]
I'll try to replicate it when work is over. Can't say much more than that now.

**Comment by ra4nd0m** [comment]
Still an issue in new version.

**Comment by ChrisAdderley** [comment]
I couldn't replicate it this morning. Do you have any other mods installed?

**Comment by ra4nd0m** [comment]
I found the culprit
It was PersistentThrust 
Unfortuanly the only way to fix this is by completely removing it.
That's a shame that such important mod for this pack is broken. Mabye this should be forwarded to PersistentThrust Github?

**Comment by ra4nd0m** [comment]
Right now I test other engines to find out how much engines are actually affected with this

**Comment by ChrisAdderley** [comment]
Quick look at the PersistentThrust source says that it adds itself to every engine. I could provide a patch to specifically remove it from engines that may have issues.

**Comment by ra4nd0m** [comment]
That would be a good idea. I will prepeare a list of affected engines.

**Comment by ra4nd0m** [comment]
Jp-10 is also affected.

**Comment by ra4nd0m** [comment]
I belive that this affects engines that require electric charge.
Yup. 
Affected engines are JP-10 and NSWR. 
I think that since low-thrust engine affected this issue should be forwarded to PersistentThrust repo.

**Comment by ChrisAdderley** [comment]
Ok. I will not do anything for now, but if we get to release without a fix I will add a patch to disable PT on those engines.

**Comment by parkerman-com** [comment]
So will it work? persistent thrust? with all engines?

**Comment by parkerman-com** [comment]
Its not working persistent thrust, any reason ?

**Comment by demonfiren** [comment]
> 
> 
> Its not working persistent thrust, any reason ?

It's been tagged "won't fix", what do you think that means?

**Comment by ChrisAdderley** [comment]
This needs to be fixed on persistent thrust's side, not mine.

**Comment by ChrisAdderley** [comment]
Closing due to above convo
