### ISSUE TITLE
NSWR golden foil texture still broken

### ISSUE THREAD

**Issue by ra4nd0m** [post-kerbin-mining-corporation/FarFutureTechnologies#118]
NSWR golden foil texture still broken
![image](https://user-images.githubusercontent.com/58385866/98026260-e7646a00-1e1b-11eb-9ce3-8804c358ae36.png)

**Comment by ChrisAdderley** [comment]
Fixed in 0.9.4

**Comment by ra4nd0m** [comment]
Fixed
