### ISSUE TITLE
Conflict with Stockish Project Orion

### ISSUE THREAD

**Issue by Calvin-13** [post-kerbin-mining-corporation/FarFutureTechnologies#136]
This mod and SuicidalInsanity's Stockish Project Orion both define ModulePulseEngine, which will probably cause problems when both are installed at once.

**Comment by ChrisAdderley** [comment]
Yargh that sucks

**Comment by Calvin-13** [comment]
I've made a pull request which renames the module to ModuleFFTPulseEngine (and renames ModulePulseEngineAnimator as well, for consistency).

**Comment by ChrisAdderley** [comment]
Is modulePulseEngineAnimator conflicted as well?

**Comment by Calvin-13** [comment]
No, I just thought the names should be consistent.

**Comment by Calvin-13** [comment]
The mods are compatible, but ModulePulseEngineAnimator is actually defined as ModulePulseEngineAnimatorAnimator.

**Comment by ChrisAdderley** [comment]
What the hecks

**Comment by ChrisAdderley** [comment]
This is all good now.
