### ISSUE TITLE
Antimatter tanks drain science

### ISSUE THREAD

**Issue by ntrepid8** [post-kerbin-mining-corporation/FarFutureTechnologies#152]
I've noticed that even if I set my antimatter tanks to have `0` antimatter in the VAB when I launch my science will still be drained to fill antimatter tanks. I'm trying to avoid paying science in exchange for antimatter and instead refine antimatter on the launchpad from fission pellets. 

- Is this a valid strategy with antimatter?
- Should I be able to launch a craft with empty antimatter tanks without draining my science?

![Kerbal Space Program_312](https://user-images.githubusercontent.com/482948/103659396-58b6bb00-4f3a-11eb-8179-0f43eb5cc7fb.png)

Also, thanks for all the terrific mods! I'm still relatively new to KSP and I can't overstate how much I've enjoyed playing with the various Near Future mods!

**Comment by ntrepid8** [comment]
Not sure if this helps, but I went and got some more science and made a step by step reconstruction with KSP 1.11 and Far Future Technologies 1.0.0 to show what I am observing:

1.) Start with 403.7 Science:
![Kerbal Space Program_320](https://user-images.githubusercontent.com/482948/103697313-bf090100-4f6d-11eb-92e7-77f39c2c2699.png)

2.) Create something in VAB with an Antimatter tank and lots of Radioisotope Generators to ensure power for containment is always available and set the Antimatter to 0.0 in the tank:
![Selection_321](https://user-images.githubusercontent.com/482948/103697533-0becd780-4f6e-11eb-938e-e9216c73dfe8.png)

3.) Click Launch and see that the Antimatter tanks are empty and click the green check to trade 0 Science for 0 Antimatter:
![Selection_323](https://user-images.githubusercontent.com/482948/103697652-38085880-4f6e-11eb-8fc4-20c6d6da814d.png)
 
*Clicking the cancel button seems to have the same behavior.*

4.) Where did all this Antimatter come from?
![Kerbal Space Program_326](https://user-images.githubusercontent.com/482948/103697867-861d5c00-4f6e-11eb-98ee-5730dd0a3d64.png)

5.) Recover the vessel and see that now we have 0.0 Science :(
![Selection_327](https://user-images.githubusercontent.com/482948/103697959-a4835780-4f6e-11eb-9fdf-d77d8f76f5d1.png)

I hope this helps. Let me know if I can provide any other information about what I'm observing and thanks again for this great mod!

**Comment by ChrisAdderley** [comment]
> Is this a valid strategy with antimatter?

It's kindof a hack but probably acceptable!

Looks like I never really tested launching things empty of antimatter, the code has several bugs in it. I will work on this.

**Comment by ChrisAdderley** [comment]
I believe this should be fixed now (well, as of a few versions ago), let me know if you see issues.

**Comment by ntrepid8** [comment]
It seems fixed to me :) Thanks!
