### ISSUE TITLE
Weird numbers for fusion fuel tanks

### ISSUE THREAD

**Issue by EnderiumSmith** [post-kerbin-mining-corporation/FarFutureTechnologies#155]
![Screenshot from 2021-01-19 14-16-20](https://user-images.githubusercontent.com/20334653/105036567-50e03600-5a65-11eb-84f4-7dc1e3a509ec.png)

First off the dry cost is weirdly low.

The Deuterium Tanks have less than half the mass of the hydrogen one but from what i can find deuterium is slightly more than double the density. This might be because the hydrogen tank is counted as a cylinder. I would also expect the helium tank to have significantly more cooling cost.

The problem is the combined tank. Its dry mass is higher than the D and He3 tanks combined. Its almost 2 D tanks combined. Also the ratio of D to He3 is wrong. It appears to be reversed. Fusion needs a 1-1 molar ratio of D and He3 which by mass is a 2-3 ratio. The tank stores about twice as much D than He however. The arbitrary units the fuel is displayed in do seem to be in a 2-3 ratio however so that might be the problem.

Also the tanks say they have 0 mass in the VAB list. The hydrogen tanks use their hydrogen containing dry mass instead.

**Comment by ChrisAdderley** [comment]
Good thoughts! Changing this is probably not going to happen, would have been better to have this input in the development phase.

**Comment by EnderiumSmith** [comment]
but the fuel switcher works on random tanks. why cant you fix the dry mass on this one?

**Comment by ChrisAdderley** [comment]
The displayed in the part list? Hardly seems worth it.

**Comment by EnderiumSmith** [comment]
no, the combined tank having twice the dry mass of the deuterium tank despite holding less mass.

also the volume ratio is 4 to 1

**Comment by ChrisAdderley** [comment]
I proposed the change on the forum. See what the average user thinks.

**Comment by ChrisAdderley** [comment]
You'll be pleased to hear that people in the forum generally support the change, so I will make it with the next update.

**Comment by EnderiumSmith** [comment]
Also a 10m tank like the one from cryotanks would be nice for actually going interstellar. i dont know what the minimum mass of an mks colony is but its probably quite heavy. with the fresnel going at 1/1000c the ship would have to be 1 third fuel.

**Comment by ChrisAdderley** [comment]
Changed in 1.1.0
