### ISSUE TITLE
Fresnel Mirror Cell Fusion Engine shutdown

### ISSUE THREAD

**Issue by the-emerald** [post-kerbin-mining-corporation/FarFutureTechnologies#157]
Hello,

I've been experimenting with the Fresnel Mirror Cell Fusion Engine. I was able to get the built-in reactor started, however the temperature of the loop would heat up to 1600K (as expected), and then the engine immediately shuts down because it has overheated. This seems to be an issue that only happens with the Fresnel engine.

![Kerbal Space Program Screenshot 2021 01 22 - 05 08 51 03](https://user-images.githubusercontent.com/12746683/105413160-ad637100-5c70-11eb-84de-f878b6f2db6a.png)

See attached for my test vessel.

**Comment by ChrisAdderley** [comment]
It's a known issue and will be dealt with in the next version.

**Comment by the-emerald** [comment]
I see. Would a temp fix like the PR help make it work meanwhile? Call me impatient... but I want to play with it!

**Comment by ChrisAdderley** [comment]
I've already changed it locally.
Your fix would somewhat fix it, but note that it's the shutdown temperature that needs to be changed, not the outlet. With your PR, you now have a mix of systems outputting 1400 and 1600K, they should be consistent at 1600K

**Comment by the-emerald** [comment]
Ah, I see! The reactor should output at 1600K and have a higher shutdown
temperature. Should I fix this, or close the PR as you've already
implemented it? Cheers.

Edit: I didn't see the PR being closed. My bad!

**Comment by the-emerald** [comment]
May I know the new shutdown temperature by the way? I assume a quick fix like upping it to 1800K would work for now

**Comment by ChrisAdderley** [comment]
1800 is the new goal.

**Comment by ChrisAdderley** [comment]
Changed in 1.1.0
