### ISSUE TITLE
Stuttering or missing sounds on several engines

### ISSUE THREAD

**Issue by LeopardEnthusiast** [post-kerbin-mining-corporation/FarFutureTechnologies#167]
The following engines play a stuttering sound while running, in addition to the expected pulse sounds:

- Impulse (Deuterium mode)
- Verne
- Casaba
- Hammertong (Reaction Products mode)

The following engines have no sound at all:
- Impulse (Deuterium/He3 mode)
- Asimov (Reaction Products mode)
- Discovery (both modes)
- Fresnel (Afterburner mode)
- Hammertong (Low Density mode)
- Cascade (both modes)

[Link to a video showing the stuttering issue](https://www.youtube.com/watch?v=PcLkmJr2VYk)

**Comment by ChrisAdderley** [comment]
Addressed for 1.2.0
