### ISSUE TITLE
Zero values for entryCost, cost and mass for fissionable and fusion tanks

### ISSUE THREAD

**Issue by hemeac** [post-kerbin-mining-corporation/FarFutureTechnologies#169]
Noticed the config files for your fissionable and fusion tanks each have some combination of 0s for entryCost, cost and mass in Far Future 1.1.4.

**Comment by ChrisAdderley** [comment]
That's because the mass and cost are handled by the tank definition.

**Comment by ChrisAdderley** [comment]
Did find a couple of entry costs that were zeroed!
