### ISSUE TITLE
Antimatter hates solar energy.

### ISSUE THREAD

**Issue by NightShift10125** [post-kerbin-mining-corporation/FarFutureTechnologies#175]
While testing the 'Frisbee' I noticed that the antimatter I brought with me had a habit of exploding.
Turns out the solar panels I used took a split second too to realign with the sun, causing the tanks to explode.
The explosions are caused when the power dips below zero, which is caused when the solar panels have to move.
Best ways I found to stop the antimatter from exploding was to use ether a reaction or a tower of solar panels which means that solar is no longer a sold method of powering ships with antimatter.

**Comment by ChrisAdderley** [comment]
Well I can't really change that if you have inconsistent power flow... I recommend packing more batteries? Sufficient to take the load if you have a few seconds of power loss.

**Comment by NightShift10125** [comment]
Believe me I had loads of batteries, 16 of the largest ones in the stock game.
But it happens so fast, you have no time to react.
Also because I forgot to but this in here are the mods I had installed, all where installed by CKAN:

B9 Part Switch
Community Resource Pack
Cryo Tanks
Cryo Tanks Core
Deployable Engines Plugin
Far Future Techologies
Module Manager
Space Dust
System Heat
Waterfall Core

**Comment by ChrisAdderley** [comment]
Ok, can you generate a reproducible test case for me? (e.g a nice simple ship I can build and teleport somewhere to observe the bug)

**Comment by NightShift10125** [comment]
I performed 3 tests with the same craft to come to the conclusion I made.
The craft is a command pod with sixteen Z-4K(s'), six large thermal control systems, twenty four fuel cells with fuel, one antimatter container, and a large solar array.
![Kerbal Space Program Screenshot 2021 08 19 - 16 12 31 95](https://user-images.githubusercontent.com/42304378/130151553-7c6c6f51-5e6e-4cb8-bf2c-efb65b6b3244.png)


For better thermal data I will be using Hot Spot and Kerbal Engineer Redux.
Was going to use a reactor but that needs Heat Control to work so I'm using fuel cells to cut down on mods.

Test 1: Does everything work the way it should.

Using the cheat menu I put the craft into orbit around the sun with a height of 12385208461 (the number is what I put in the cheat menu, gives you a orbit between Kerbin and Eve).
Then I put on infinite electric charge and infinite propellant to see if the craft could keep it together for a one year flight.
Or in my case until the craft goes blue (very cold).
![Kerbal Space Program Screenshot 2021 08 19 - 16 13 40 94](https://user-images.githubusercontent.com/42304378/130151589-d76ec48e-d9bf-4645-9851-d2ac1a067a1c.png)


Test 2: Can the fuel cells keep the craft from exploding.

I turned off infinite electric and let the fuel cells run to see if anything would happen.
Everything seemed to be fine until I reached the highest time warp and everything overheats...

The power doesn't even run out it just explodes!
https://user-images.githubusercontent.com/42304378/130151740-1e751f91-3288-4d75-bd14-6300b19584d5.mp4

Here's the same craft without the antimatter:
https://user-images.githubusercontent.com/42304378/130152021-265d5cdd-2454-40c1-a3da-ab843fc64b3f.mp4

**Comment by ChrisAdderley** [comment]
Thanks. Is there a particular reason you have all those control systems on it?
edit - I've actually just realized you don't have dynamic battery storage installed according to your list, which is a requirement. Can you install it and check again?

**Comment by NightShift10125** [comment]
Ship go boom.

**Comment by ChrisAdderley** [comment]
Ok so I'm trying to get this case working. Your ship will always explode, I think, because 24x fuel cells @ 1.5 Ec/s= 36 Ec/s, and the container you have uses 60. So boom.

I tried a case with a similar ship, that uses 4x large fuel cells which do provide enough power:

![screenshot138](https://user-images.githubusercontent.com/5642064/130182235-ce65081c-4a04-421e-b402-de30ed46e5b6.png)

This was stable at full timewarp, no issues, though it eventually burned through all its fuel and boom. 

More investigation tomorrow.

**Comment by NightShift10125** [comment]
I did some more testing on my end, this time with; Near Future Solar, and Near Future Electrical installed.
I found that the reactors both nuclear and fission could provide enough power while the ship still explodes if being powered by fuel cells or less than a dozen solar panels facing the sun.

https://user-images.githubusercontent.com/42304378/130263241-1bf4ff6e-6601-46ec-931f-d0680f7b5e42.mp4
https://user-images.githubusercontent.com/42304378/130262668-0025a9a1-a608-4cd0-9e65-0448fdd1a865.mp4
https://user-images.githubusercontent.com/42304378/130262889-b39ef45f-8377-4dd5-b43b-fd42142ce309.mp4

**Comment by ChrisAdderley** [comment]
I added a compensation mechanism that will stop antimatter exploding for a few physics frames. This should help with jittery power sources. 

However in my own testing it's pretty hard to get the geometry right unless you have some sort of timewarp tracking mod to keep the ship pointed in the ideal orientation for its panels. You effectively need a perfectly stable energy supply and solar on an orbiting craft really isn't it.

**Comment by ChrisAdderley** [comment]
Increased comp timing to 30 physics frames.
