### ISSUE TITLE
Suggestion: make "bussard" particle scoop extendable in VAB

### ISSUE THREAD

**Issue by Hoskja** [post-kerbin-mining-corporation/FarFutureTechnologies#180]
It would be useful for ship design and planning to have the particle scoop able to extend in the VAB.

**Comment by ChrisAdderley** [comment]
This has to be done in Space Dust, so addding this: https://github.com/post-kerbin-mining-corporation/SpaceDust/issues/44

**Comment by ChrisAdderley** [comment]
Resolved in Space Dust 0.4.3
