### ISSUE TITLE
Vulcan refinery won't refurbish ablator on Casaba, says ablator full

### ISSUE THREAD

**Issue by danfarnsy** [post-kerbin-mining-corporation/FarFutureTechnologies#184]
When I try to use Vulcan refinery to refurbish ablator for the Casaba engine, the refinery output says "ablator full" in the PAW even when the ablator is empty or partially spent. I have ore and a level 3 engineer. I'm able to make other nuclear fuels without issue. I also tested with a heat shield with ablator depleted, which gets the same PAW message.

![image](https://user-images.githubusercontent.com/13547273/142291144-dc1e7248-301c-4b96-a6b0-27f5315d9e51.png)

Probably not related, but the config for fft-nuclear-smelter-375-1 also has the ratio of ablator from ore at 0.001, which is 1000 ore per ablator,  or 17 million ore to fully refurbish the Casaba. Changing this ratio to 10:1 or even 1:10 for testing did not affect the "ablator full" issue above, however.

**Comment by ChrisAdderley** [comment]
Functionality removed because it's not supported by resource flow stuff
