### ISSUE TITLE
Optional patch so antimatter does not cost science but costs a lot. 

### ISSUE THREAD

**Issue by ThingsMadeHere** [post-kerbin-mining-corporation/FarFutureTechnologies#185]
Like a billion per gram. It does not make sense that to get antimatter, the kerbals need to research it even more. by the time the do get antimatter tech, they would have already traveled to other stars, and already know about all of the properties of antimatter. please make a patch to replace science cost with funds cost.

**Comment by ChrisAdderley** [comment]
Well this is a gameplay choice versus a "realism" feature, and you can turn it off in settings.
