### ISSUE TITLE
Combined ²H₂/³He tanks have higher dry mass than sigle type

### ISSUE THREAD

**Issue by EnderiumSmith** [post-kerbin-mining-corporation/FarFutureTechnologies#189]
The single fuel variants have 17% dry mass like the normal hydrogen tanks but then combined fuel version has 19% instead. The correct dry mass per unit is 0.00007968

**Comment by JacobB094** [comment]
Is this really a bug? I thought this accounted for the fact that you need some kind of bulkhead to separate both fusion fuels, hence the mass penalty. It shouldn't be the case with tanks that are made up of discrete spheres already, but many are just one big sphere, which would presumably need another inside to hold two fuels.

**Comment by ChrisAdderley** [comment]
Change in latest relese anyways
