### ISSUE TITLE
Rename Antimatter storage part module to be generic instead of specific

### ISSUE THREAD

**Issue by 321nick** [post-kerbin-mining-corporation/FarFutureTechnologies#193]
The ModuleAntimatterTank part module can have the resource it contains changed in the part config, but it will always show up in the right click menu as "antimatter containment", even when its changed to contain a different volatile resource. This is misleading to the end user if another mod (which i am making) using the plugin was to use the part module to model the containment of a different volatile resource.

If the title of the part module was changed to be something generic, like "Volatile tank" or "volatile containment", and the note about antimatter costing science was moved (maybe have it be at the top of the parent part's description, or have it toggleable on a per-part basis as a field in the partmodule, like how DetonationRate is), then the part module could be used  with any resource that is volatile and can fail catastrophically when not actively cooled/contained, without being misleading to the end user.

**Comment by ChrisAdderley** [comment]
You can do this already by changing this line: https://github.com/post-kerbin-mining-corporation/FarFutureTechnologies/blob/3c32b38086f8873b0cdaceab8fb041ff425a08b5/GameData/FarFutureTechnologies/Localization/en-us.cfg#L460

**Comment by 321nick** [comment]
That works, i didnt realize i could just overwrite the localization key. Thank you for the reply.

**Comment by ChrisAdderley** [comment]
No worries, I try to make it as configurable for the end user as possible.
