### ISSUE TITLE
Disabling "Antimatter Costs Science" in diffculity setting won't work

### ISSUE THREAD

**Issue by randomguyingithub** [post-kerbin-mining-corporation/FarFutureTechnologies#200]
![KSP_x64_2410171747_tPX8M](https://github.com/user-attachments/assets/33f29a5d-35f7-4156-8edf-d029746fa6a3)
![KSP_x64_2410171747_lSl25](https://github.com/user-attachments/assets/2024e0c2-4e4e-4bb9-9f13-6a668a25d369)

Tested both disabling during creating new save and during ingame. The game still asking for science point. Clicking tick button won't load antimatter due to lack of science point.

Other info: Science mode, used Cheat console to unlock all tech for quick reproduction

KSP + Player log + module manager cache: [fftreport.zip](https://github.com/user-attachments/files/17410038/fftreport.zip)

**Comment by ChrisAdderley** [comment]
Fixed in 1.4.2, the setting was only working in Career.
