### ISSUE TITLE
AM container explodes when timewarping

### ISSUE THREAD

**Issue by Jimbodiah** [post-kerbin-mining-corporation/FarFutureTechnologies#29]
Hi Chris,

In case you didn't already know: The AM container blows up when going into time-warp (around 3-4th step). I removed the energy requirement (0) and the problem is gone. Probably EC production is not checked during time warp as I have ample supply to keep the container charged.

Great mod btw! Hope you eventually release it.

**Comment by ChrisAdderley** [comment]
It would be nice to get a picture of the ship, or better, a craft file. This is the same issue that occurs with CryoTanks and I would like more data.

**Comment by ChrisAdderley** [comment]
This should probably be resolved in the next build.
