### ISSUE TITLE
Metallic Hydrogen Tanks

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/FarFutureTechnologies#40]
Fancy tanks to contain MetHydrogen

- [x] 2.5m
- [x] 3.75m
- [ ] 5m

**Comment by Kerbas-ad-astra** [comment]
A 'Hydrogen Compressor' would also be a good part, to let MetHydrogen be synthesized from LqdHydrogen.

(Also, maybe "MtlHydrogen" would be a better term, analogous to "Lqd"?  Squad's forum sometimes has trouble with the [Scunthorpe problem](https://en.wikipedia.org/wiki/Scunthorpe_problem).)

**Comment by ChrisAdderley** [comment]
I am reluctant to scope another resource conversion part, but we will see.

The resource definition will be decided at a later date, but MtlHydrogen is probably best.
