### ISSUE TITLE
Antimatter engines don't show DV in the VAB

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/FarFutureTechnologies#42]
... because you can't put fuel in them in there. In KER and MJ.

Change the procedure so that they start with full fuel loads, but this isn't carried over to the launch scene.

**Comment by gabevenberg** [comment]
dont force full fuel loads, but allow us to tweak it. that way, we can say, make a mission to jool with just enough AM to get there, gather AM, and get back with extra.

**Comment by ChrisAdderley** [comment]
Should now be resolved
