### ISSUE TITLE
no AM in kerbin exo?

### ISSUE THREAD

**Issue by gabevenberg** [post-kerbin-mining-corporation/FarFutureTechnologies#44]
if im reading the AM .cfgs right, there should be antimatter somewhere between 600Km and 1200Km on kerbin, but it seems that there is none anywhere to be found. to be sure, i looked in the entire altitude range of kerbin, from 70 km to beyond minnmus orbit. 
jool does have AM as expected.

**Comment by ChrisAdderley** [comment]
Should be resolved in the next version...
