### ISSUE TITLE
pw 2x nuculear pellet storage container holds 400 more pellets than pw 4x

### ISSUE THREAD

**Issue by gabevenberg** [post-kerbin-mining-corporation/FarFutureTechnologies#46]
2x has 4000 volume, 4x has 3600.
what are the numbers meant to be?

**Comment by ChrisAdderley** [comment]
Check https://github.com/ChrisAdderley/FarFutureTechnologies/blob/master/changelog.txt, I try to keep a list of fixed issues in the dev branch of each git, but this repo only has a master branch right now.

**Comment by ChrisAdderley** [comment]
Resolved
