### ISSUE TITLE
Request: Fission Fragment Rocket? (dusty plasma and/or rotating disks)

### ISSUE THREAD

**Issue by gabevenberg** [post-kerbin-mining-corporation/FarFutureTechnologies#47]
according to this:
http://www.projectrho.com/public_html/rocket/enginelist.php#fissionfragment
and this:
https://en.wikipedia.org/wiki/Fission-fragment_rocket#Rotating_fuel_reactor

rotating disks may be lower on the tech tree, (possibly even in the Kerbal Atomics mod, with the gas cores), but would have a lower specific impulse, (from what i can find, around 100k s) and the fuel would not be transferable without EVA. (or, due to radiation concerns, not refuelable whatsoever.) cant find the thrust. might be more compact, perhaps fitting in a 2.5m form factor.

dusty plasma would be higher on the tech tree, definitely in far future, specific impulse from 500k s to 1M s, and draw uranium directly from tanks. may need to 'charge up' (using your new plugin) with uranium before starting. the low density of the reaction chamber would make this engine at least a 3.75m form factor. online resources suggest 20-40 N of thrust, but you may have to increase that for gameplay reasons.

what do you think? i know you have a lot to do already, but this is just one more idea for the ever growing checklist.

**Comment by ChrisAdderley** [comment]
I think the problem with this one is that it's yet another low-thrust high-efficiency engine. I've got a few of those already... I guess this is a ridiculously high-impulse one, but thrust-wise the engines produce on the order of 300-500 N.

**Comment by gabevenberg** [comment]
it is extreme ISP, only beat by the beamed core drive, and earlier in the tech tree. however, the lowest TWR of any engines in any of your mods.
For thrust, you may want to go with sub kN, or, you could scale it with the stock ion, assuming the stock ions real counterpart has .25N, according to my thrust value (taken from the atomic rockets website, dunno where you got yours, seems kinda high.), your thrust would be 22.4 KN. In a 2.5M-2.75M and at least 10 tons for the dusty plasma, probably more for the rotating disks (fuel is included in engine for rotating disks, seperate for dust.), it makes it by far the lowest TWR engine in all mods I know of. 
I admit, you do have a lot of low thrust-high ISP engines, but this one takes the cake, and the fission-fragment rocket is a very unique concept that has not been covered in any other mods, and one that I, personally would very mutch like to see. Still, i know you have a lot on your plate right now with the other parts that need doing and the upcoming update.

**Comment by ChrisAdderley** [comment]
Scoping a 3.75m version of this in, using the Werka design specs. Probably aiming at 550,000s with thrust around 50 kN, mass 15-20t.

**Comment by ChrisAdderley** [comment]
Completed, will be in next version
