### ISSUE TITLE
FFE thrust offset

### ISSUE THREAD

**Issue by gabevenberg** [post-kerbin-mining-corporation/FarFutureTechnologies#63]
as shown in the screenshot, even when it is the only part on a vessel, the fission fragment engine exerts  about half a kNm. the .cfg looks normal, so im thinking it may be an issue with the location of the ThrustTranform?

http://imgur.com/LwX9R8G

**Comment by ChrisAdderley** [comment]
I'll check it out. It's probably off-centre colliders, it always is...

**Comment by ChrisAdderley** [comment]
Resolved in 0.2.4
