### ISSUE TITLE
Inertial Confinement Fusion Engine

### ISSUE THREAD

**Issue by ChrisAdderley** [post-kerbin-mining-corporation/FarFutureTechnologies#94]
Based off of Hyde design

- [ ] Model
- [ ] Unwrap
- [ ] Texture
- [ ] Integration
- [ ] Plugin Components

**Comment by HiBobByeBob** [comment]
Are we getting a new release soon ?

**Comment by ChrisAdderley** [comment]
Worth reviewing the dev thread.

**Comment by ChrisAdderley** [comment]
Done.
